### ISSUE TITLE
weapon choices

### ISSUE THREAD

**Issue by Defcon5-1** [NeoArmageddon/co10_Escape#100]
I run an ARMA3 escape server . I have the mod SMA weapons installed and correctly in the command line  but the guards still start with vanilla weapons. 
After a non specific time 2-10 mins or so the weapons change in the guards hands. 
How do I force the guards to carry SMA weapons. (or any other weapon pack)?

Many thanks

**Comment by NeoArmageddon** [comment]
You don't. That is not how Arma3 missions and mods work and actually I have no idea why the weapons change after a few minutes but I suspect this weapon mod is replacing weapons on units by a script. If you are unhappy with the delay in replacement, the author of the weapon mod is the best person to ask.

To have different weapons in a mission (like Escape) you need to edit the mission and add the weapon class names explicitly. That is (in most cases) beyond the scope of a regular player and involves modding and scripting.
