### ISSUE TITLE
new Earplugs function fails if not using CBA

### ISSUE THREAD

**Issue by AKA-TiTAN** [NeoArmageddon/co10_Escape#102]
i am aware this is a dev version, but the new Earplugs function fails for non CBA users.

i amended my fn_initlocalplayer.sqf for a CBA check and used alternative config if not found. 

If (isclass (configfile >> "CfgPatches" >> "cba_main")) then {
	[] spawn {
    disableSerialization;
    ["A3E Earplugs", "toggle_earplugs_key", localize "STR_A3E_initLocalPlayer_toggleEarplugs", {_this call A3E_fnc_toggleEarplugs}, ""] call CBA_fnc_addKeybind;};
	} else {
	[] spawn {
	disableSerialization;
	waitUntil {!isNull(findDisplay 46)};
	systemChat "Push INSERT key to toggle earplugs";
		(findDisplay 46) displayAddEventHandler [	"KeyDown",{	params ["_display","_key","_shift","_ctrl","_alt"]; private _handled = false; 
		if (_key isEqualTo 210) then	// INSERT KEY
				{	_this call A3E_fnc_toggleEarplugs;
					_handled = true;
				};
			_handled
			}
		];
	};
};

**Comment by NeoArmageddon** [comment]
Heyho, it is known that this does not work without CBA keybindings and there will be no added key as fallback, as there is no way for the player to change the keybinding (without adding something like the CBA system itself, which is an overkill).
Added fixed keybindings to a mission is in my opinion a bad practise and can render the mission for some players unplayable.

**Comment by FlorianSW** [comment]
However, does this mean, all users need to have CBA keybindings as an addon installed, otherwise the mission crashes for them? If so, we should probably at least add the cba check, to prevent trying to add the keybinding if cba is not present? This would allow the mission to be playable by people without CBA installed.

**Comment by NeoArmageddon** [comment]
Users without CBA just don't have the option to set a keybinding. There is no dependency on CBA.

**Comment by FlorianSW** [comment]
Okay, then it's fine for me :) just wanted to make sure this doesn't break the mission when started without cba :)

**Comment by AKA-TiTAN** [comment]
FlorianSW
if you are interested in my  params.hpp i have added an option for the admin to set the 'use action #' that is under "options controls - custom controls" 

	class A3E_Param_Earplug
	{
		title="Custom user action setting for admins to set assignment of Earplug key (if CBA not in use)";
		values[]={1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20};
		texts[]={"ACTION 1","ACTION 2","ACTION 3","ACTION 4","ACTION 5","ACTION 6","ACTION 7","ACTION 8","ACTION 9","ACTION 10","ACTION 11","ACTION 12","ACTION 13","ACTION 14","ACTION 15","ACTION 16","ACTION 17","ACTION 18","ACTION 19","ACTION 20"};
		default = 20;
	};

then under fn_initlocalplayer.sqf 

replace the last []spawn section with :-

If (isclass (configfile >> "CfgPatches" >> "cba_main")) then {
	[] spawn {
    disableSerialization;
    ["A3E Earplugs", "toggle_earplugs_key", localize "STR_A3E_initLocalPlayer_toggleEarplugs", {_this call A3E_fnc_toggleEarplugs}, ""] call CBA_fnc_addKeybind;};
	} else {
	[] spawn {
	disableSerialization;
	waitUntil {!isNull(findDisplay 46)};
		(findDisplay 46) displayAddEventHandler [	"KeyDown",{	
		private _NUM = A3E_Param_Earplug;
		private _key = "user" + (str _NUM); 
		private _USR = actionKeys _key select 0;
		params ["_display","_key","_shift","_ctrl","_alt"]; private _handled = false; 
		if (_key isEqualTo _USR) then
				{	_this call A3E_fnc_toggleEarplugs;
					_handled = true;
				};
			_handled
			}
		];
	};
};

this will give the admin the ability to assign which user action the player needs to edit (so if another mod they are using has a predefined  user action assigned they can change it) , and the player then can set the key in options-controls-custom control.

ie: the default  Action 20 in the params.hpp, so the player assigns a custom key to Use Action 20.
