### ISSUE TITLE
Dystopian's Remove HMD from inventory fix no longer works.

### ISSUE THREAD

**Issue by Qerbas** [NeoArmageddon/co10_Escape#103]
There's an issue where on certain CUP versions they add NVGs to the vest or uniform on units.  These should be removed, especially when the "No NVG" parameter is selected, to prevent cheating.  Dystopian made a fix with [these commits](https://github.com/NeoArmageddon/co10_Escape/commit/34dfb5635a23ea36469f5ee5e6cee02b13860539), however they have not worked for a while.  It is not related to the recent parameter refactoring since I tested a version without those new changes and the issue still occurs.  I'm not sure exactly when the issue started, but I believe it was at least a few months ago. 

You can test by going to any unit (except for the prison guards) and checking the uniform/vest/backpack for an NVG.

I tried just copy pasting Dystopian's fix into the new fn_onEnemySoldierSpawn.sqf file, however it doesn't work and I get an error.  Here's a screenshot of that error.

![ArmA 3 Screenshot 2021 02 09 - 00 00 46 85](https://user-images.githubusercontent.com/53233871/107334600-c3907000-6a6b-11eb-88cf-a50b7af3293b.png)

**Comment by NeoArmageddon** [comment]
In fn_onEnemySoldierSpawn.sqf the var is __unit_ not __this_ . ;)

**Comment by Qerbas** [comment]
Yeah that seems to work, thanks for the help.
