### ISSUE TITLE
fallujah is not working properly

### ISSUE THREAD

**Issue by marhub** [NeoArmageddon/co10_Escape#112]
description: 
prison and ai are spawning above ground or below ground.

steps to reproduce:
1. download Fallujah 1.2 https://steamcommunity.com/sharedfiles/filedetails/?id=908733096&searchtext=fallujah
2. run CSAT vs NATO ( or NATO vs CSAT Fallujah ).

expected result: 
mission works :) 
actual result:
![20210324211619_1](https://user-images.githubusercontent.com/2960432/112391736-a69cbd00-8cf8-11eb-811b-ae3615679334.jpg)
sometimes AI and prison building is about 20m above ground, sometimes it seems that it's on the right level, but the building has no walls ( it has only the sandbag wall ) and backpack is missing ( perhaps below ground ? ).

Server restart does not help, it happens to all clients connected to that serever.

**Comment by Qerbas** [comment]
Which version are you running?  Also what mods are running on your client/server?  I've played fallujah many times on many different versions and have never seen this happen.

**Comment by marhub** [comment]
@Qerbas  Can you confirm that you were playing "Fallujah 1.2" downloaded from steam? ( link in issue description )
My first thought was that escape mission was made for another Fallujah version with bit different coordinate systems ( I'm not familiar with how maps and mods work in ARMA, that's just programmers guess ;).

I have the latest ARMA, latest escape, and map from the link above ( also the latest version of it ).
I have a bunch of other mods enabled, I'll try later disabling them and will let you know if that helps.
Server logs did not show any relevant errors.

**Comment by marhub** [comment]
Ok, just tried with minimal mods enabled.
Mission file: `co10_Escape_BIS_CSAT_vs_NATO.Fallujah`
Mods: <pre>CUP Terrains - Core
CUP Terrains - Maps
Fallujah v1.2 </pre>

**Not working properly**
Some more screenshots attached.
![107410_screenshots_20210326121657_1](https://user-images.githubusercontent.com/2960432/112624660-355f2600-8e2e-11eb-8b60-2cbaa92ed04f.jpeg)
![107410_screenshots_20210326121712_1](https://user-images.githubusercontent.com/2960432/112624662-35f7bc80-8e2e-11eb-9250-694dfa69ccab.jpeg)
![107410_screenshots_20210326121715_1](https://user-images.githubusercontent.com/2960432/112624664-36905300-8e2e-11eb-861f-94e7f9ddf1e6.jpeg)
![107410_screenshots_20210326121735_1](https://user-images.githubusercontent.com/2960432/112624667-37c18000-8e2e-11eb-9ab9-c2b63d649590.jpeg)

**Comment by NeoArmageddon** [comment]
Heyho,
this happens if server and client version of a terrain don't match and/or the server has failed to load the terrain (it will fallback to the previously loaded terrain).

This can't be a problem with the mission as the prison prison and player spawning is not even taking the height into account and is always "on ground".
Also from your latest screenshot:
The only global building (aka spawned on server) and the AI is in the air, while all elements from the prison that are spawned locally are at the ground. Conclusion: Terrain is different on server and client.

**Comment by marhub** [comment]
Yep, i do confirm that it was issue with server not loading terrain.
Fixed now. Can be closed. Thanks!
