### ISSUE TITLE
Script Errors in DEV version

### ISSUE THREAD

**Issue by MildlyInterested** [NeoArmageddon/co10_Escape#114]
**Mission & Version**
Running the `co10_Escape_CUP_Woodland_USMC_vs_RU_and_NAPA` compiled by the EscapeDevPacker 1.7.
Downloaded on 2021-04-11.

**Mods & Players**
Used modlist available here: https://armapresetcreator.com/2346613458
Was running the mission with 10 Players, including some join in progress players.

**Script Errors**
All errors which were logged in the RPT over the duration of 2.5 hours.

5 times:
```sqf
23:02:41 Error in expression <n (units _group select 0);
_lastPos = + _currentPos;
_lastMoveTime = diag_tickTi>
23:02:41   Error position: <_currentPos;
_lastMoveTime = diag_tickTi>
23:02:41   Error Undefined variable in expression: _currentpos
23:02:41 File functions\DRN\fn_SearchGroup.sqf [drn_fnc_SearchGroup]..., line 160
```

3 times:
```sqf
23:15:41 Error in expression <n {
systemchat ("Delaying rain by "+str _time + " seconds");
params["_rain","_ti>
23:15:41   Error position: <_time + " seconds");
params["_rain","_ti>
23:15:41   Error Undefined variable in expression: _time
23:15:41 File functions\Server\fn_weather.sqf [A3E_fnc_weather]..., line 82
```

2 times:
```sqf
23:34:14 Error in expression < units _this select 0;
while {!(isNull _unit)} do {
_enemyUnit = _unit findNear>
23:34:14   Error position: <_unit)} do {
_enemyUnit = _unit findNear>
23:34:14   Error Undefined variable in expression: _unit
23:34:14 File functions\Server\fn_initServer.sqf [A3E_fnc_initServer]..., line 294
```

**Comment by NeoArmageddon** [comment]
Does not look an error in escape but some faulty 3rd party scripts or to much load oon the server that mess with units/variables. All those errors are from some loops and if the script really failed, they would repeat indefinitly. 

I cannot reproduce these on my server.

**Comment by MildlyInterested** [comment]
True, not game breaking.
Server was under heavy load when these errors occured (<30FPS) so sounds about right. 
Thanks for taking a look!
