### ISSUE TITLE
Western Sahara missions have no slots

### ISSUE THREAD

**Issue by Vormulac** [NeoArmageddon/co10_Escape#129]
Western Sahara missions don't seem to have slots.  Will continue to test and report back.

**Comment by ScruffyAT** [comment]
Current compile (should be same as dev packer) works for me on windows dedi, tested both WS versions and a CUP one on Sefrou-Ramal, and a WS version on Stratis. 
Was it terrain, units, or both?
Did the server properly start with WS? Missing slots is often a missing addon error, and I know steamcmd sometimes messes up the updates for us.

**Comment by Vormulac** [comment]
Yeah that's what I'm starting to think too.  I was able to load the terrain fine but never got any slots.  I tried loading a blank mission with a non WS playable unit and it loaded so I think something is wrong with the install.  I'm running an armahost server so I'll check with support to see if WS is installed correctly.

**Comment by Vormulac** [comment]
Was an issue with the installation on armahosts' end.  It's been taken care of, definitely have slots now.
