### ISSUE TITLE
Found an almost drop in sandstorm script

### ISSUE THREAD

**Issue by lozanoeg** [NeoArmageddon/co10_Escape#135]
I saw mention of adding sandstorms to desert map and I found a pretty good script. here are screenshots from my escape mission as it is now
![image](https://user-images.githubusercontent.com/28077452/148877384-590d5304-063b-4647-9aa5-19fdcc166c6a.png)
![image](https://user-images.githubusercontent.com/28077452/148877414-f9f66adb-c081-4074-9814-fc015c3e3a7b.png)
![20220110215612_1](https://user-images.githubusercontent.com/28077452/148962779-c06e22cd-b72a-40d6-b6c1-d4fc6b4e01e9.jpg)
![20220110215004_1](https://user-images.githubusercontent.com/28077452/148962790-bf9b222b-e28d-4a7d-99ff-1c91e3b35280.jpg)
![20220110214953_1](https://user-images.githubusercontent.com/28077452/148962815-8e9be461-5b9c-4410-a4bb-9812d5088d3d.jpg)

You can control the intensity by the level of fog and the duration of the script. It has some other features like your gun aim is difficult until you have glasses/goggles and things like that. the script does need a little modifying to remove some of the radio noises that it comes with but it should be fairly easy to implement

[sandstorm demo mission to get script](https://www.dropbox.com/s/cpkosg5swbor3qv/ROS_sandstorm_V4_5_demo.Altis.zip?dl=0)

**Comment by NeoArmageddon** [comment]
Hiho and thanks for your suggest.

Unfortunatly the scriptis not compatible with the Escape framework without much change to the underlying scripts. This feature must also be limited to desert terrains is IMHO not worth the effort and the potential risk. Also the license of the linked scripts are not clear.

Such effects can always be added on a addon/serveraddon basis which is a much more community/admin friendly way for such (cosmetic)-features.

**Comment by lozanoeg** [comment]
Sorry i thought i linked where it came from https://steamcommunity.com/sharedfiles/filedetails/?id=2120439820 he never said anything about licensing other then just credit him if you use it but i can understand it wouldn't be easily integrated with the current framework
