### ISSUE TITLE
a3e_arr_AmmoDepotOrdnance frequently doesn't spawn.

### ISSUE THREAD

**Issue by Qerbas** [NeoArmageddon/co10_Escape#19]
I've noticed in testing that this box doesn't spawn almost half of the time.  I'm unsure how long this has been the case, but it's highly consistent.  This occurs both in editor testing and on a dedicated server.  I've attached a few examples of this happening.

![ArmA 3 Screenshot 2019 08 15 - 16 14 50 30](https://user-images.githubusercontent.com/53233871/63704897-e4fe8d00-c7e0-11e9-98dd-590ade064832.png)
![ArmA 3 Screenshot 2019 08 15 - 17 22 19 90](https://user-images.githubusercontent.com/53233871/63704923-f051b880-c7e0-11e9-8519-b95e36cae08e.png)
![ArmA 3 Screenshot 2019 08 15 - 17 13 42 02](https://user-images.githubusercontent.com/53233871/63704924-f051b880-c7e0-11e9-815a-ab161e0c521b.png)
![ArmA 3 Screenshot 2019 08 15 - 17 14 39 29](https://user-images.githubusercontent.com/53233871/63704925-f051b880-c7e0-11e9-889e-4033ab0514f6.png)

**Comment by jaj22** [comment]
The boxes aren't created if there's nothing in them. Because there are few items in the list for the ordnance box, there's a decent chance that it won't appear. Occasionally happens with the launcher box too, but that's much rarer.

**Comment by NeoArmageddon** [comment]
Exactly, that is intended behaviour so there are no empty boxes.
