### ISSUE TITLE
Prevent prison from spawning near the airfield.

### ISSUE THREAD

**Issue by Qerbas** [NeoArmageddon/co10_Escape#21]
The porting instructions indicate that the prison is supposed to spawn away from airfields, however the prison can and will spawn directly on the airfield.  While this can be funny sometimes, it greatly increases the difficulty of the mission and makes dodging the scout helicopter almost impossible.  Having it so the prison can't spawn with around 1KM should do the trick without affecting smaller maps too much.  Porto being the only exception, but it'll still be playable.  

![ArmA 3 Screenshot 2019 08 26 - 13 25 53 50](https://user-images.githubusercontent.com/53233871/63985987-d0dbb980-ca86-11e9-9a83-350181fca1a2.png)

![ArmA 3 Screenshot 2019 08 26 - 13 26 01 16](https://user-images.githubusercontent.com/53233871/63985993-d6390400-ca86-11e9-818d-7c65bed18896.png)

**Comment by ScruffyAT** [comment]
Just place markers named "A3E_ExclusionZone" (and A3E_ExclusionZone_1, A3E_ExclusionZone_2 , etc.) in mission.sqm like this. 
Markers will only stay visible if debug is on
![20200801233206_1](https://user-images.githubusercontent.com/50166100/89110865-79408d80-d44f-11ea-80b2-f9ef1af8b212.jpg)

**Comment by BeardedBushman** [comment]
Yeah it makes it really hard when you are playing solo.
