### ISSUE TITLE
Add a parameter that allows players adds flashlights to all units.

### ISSUE THREAD

**Issue by Qerbas** [NeoArmageddon/co10_Escape#25]
Escaping in the middle of night is a very fun idea and fits the theme of the mission, however in it's current state it isn't really possible.  At night taking out the prison guards can be nearly impossible. They can spot you easily because of the lights in the prison lighting you up, and if they spawn away from the prison without flashlights it can be nearly impossible to see them.  Not only that, but if you do manage to take out the prison guards they probably won't have flashlights and neither will most of the random patrols, so starting at night isn't really an option.  Starting at dusk and trying to horde NVGs is the only viable way, but doing that somewhat defeats the point of playing at night.  It would be nice to play escape with the no NVGs option while being able to navigate the environment easily.  It would also add a nice bit of variety to the mission.

A binary parameter that adds the default flashlight to all primary weapons carried by enemies would be a good way to do this, and nearly every weapon in Vanilla, CUP, and RHS are can use the default flashlight.  Some mods, like IFA3, don't work but editing the parameter to say something like "Add flashlights to all units (does not work with all weapons/mods)" to inform the player will help.  In addition to this, the parameter should also add a couple regular flashlights and pistol flashlights to the backpack to help the players.  By default the parameter would off, and if the player wants to play at night they can enable it if they desire.

**Comment by NeoArmageddon** [comment]
This should be incorporated with https://github.com/NeoArmageddon/co10_Escape/commit/e1a90060701b23720db47e45de325b367c03ba19
There is no special param, NVs are still controlled by the old param but now atleast every patrol unit should get atleast a flashlight at night. Doesn't make much sense to send out guards without light or NV at night.
