### ISSUE TITLE
Village Patrol Spawns Parameter not functioning properly

### ISSUE THREAD

**Issue by Qerbas** [NeoArmageddon/co10_Escape#43]
After the rework of the village patrol spawns I've noticed that markers are spawning a lot more AI than usual.  I tested the different settings and it looks like there is minimal difference between the three different settings on the new system, whereas there are dramatic differences in the old system.
The scaling really needs to be dialed back and ideally should be made to be more linear than the old system.  There's a massive difference between medium and high but not much between low and medium.

Here's some screenshots that demonstrate this:

NEW SYSTEM

Village Patrol Spawn High spawns about 17
![ArmA 3 Screenshot 2019 12 22 - 12 02 03 03](https://user-images.githubusercontent.com/53233871/71326678-fd429800-24b2-11ea-8736-3c2397560f91.png)

Village Patrol Spawn Medium spawns about 15
![ArmA 3 Screenshot 2019 12 22 - 11 59 40 67](https://user-images.githubusercontent.com/53233871/71326654-a472ff80-24b2-11ea-883d-acbba38bc7e8.png)

Village Patrol Spawn Low spawns about 13 squads for this marker
![ArmA 3 Screenshot 2019 12 22 - 11 48 22 57](https://user-images.githubusercontent.com/53233871/71326598-ef404780-24b1-11ea-85a2-5dc04a90e151.png)

OLD SYSTEM

Village Patrol Spawn High spawns about 12
![ArmA 3 Screenshot 2019 12 22 - 12 10 53 43](https://user-images.githubusercontent.com/53233871/71326761-77bfe780-24b4-11ea-9b57-a8db96507658.png)

Village Patrol Spawn Medium spawns about 4
![ArmA 3 Screenshot 2019 12 22 - 12 09 34 26](https://user-images.githubusercontent.com/53233871/71326745-53640b00-24b4-11ea-8f2c-1ff1d8928da1.png)

Village Patrol Spawn Low spawns about 2
![ArmA 3 Screenshot 2019 12 22 - 12 07 26 32](https://user-images.githubusercontent.com/53233871/71326743-45ae8580-24b4-11ea-953b-10ca3a9c6ae1.png)

BONUS

Old system Mid city on fallujah Village Patrol Spawn Low spawns a couple dozen patrols
![ArmA 3 Screenshot 2019 12 22 - 12 18 08 58](https://user-images.githubusercontent.com/53233871/71326845-4dbaf500-24b5-11ea-9913-e77774095008.png)

New system Mid city on fallujah Village Patrol Spawn Low spawns at least a _hundred_ patrols
![ArmA 3 Screenshot 2019 12 22 - 12 23 08 39](https://user-images.githubusercontent.com/53233871/71326894-de91d080-24b5-11ea-8ba7-6a217a27b216.png)

**Comment by NeoArmageddon** [comment]
Hehe, yes, the scaling is just guessed. Maybe I should finetune it^^

**Comment by NeoArmageddon** [comment]
Should work much better now in Dev 19-12-23

**Comment by Qerbas** [comment]
Unfortunately the latest changes don't really seem to be much of a difference, and they seem to make the parameter settings largerly non functional.  The same amount of AI are spawning regardless of setting. I made sure to load the master branch with none of my alterations.  I've also noticed that the group sizes in the village patrol spawns are not scaling with the group size parameter like they did on the old system.  It's always spawning group sizes of 2-4.

I should have been more clear by what I mean by more linear.  What I meant is that think for the most part the old system was good on the medium and low settings for markers of size 200x200 and below, but on larger markers and especially the high village patrol spawn setting the AI counts got way too high and made city performance tank.  Fallujah has unplayable performance on anything but the low village patrol spawn setting.

For example, on the example marker where I've been doing most of my testing, I think on the old system for that marker the low and medium patrol amount is pretty good.  4 patrols on medium doesn't sound like a lot, but when coupled with a group size of medium that's still about 24 soldiers which is still a good number of troops.  Especially since random patrols will start coming in to support them.  It's already a great challenge.  Maybe bumping it up to about 6 patrols max but that might have cascading effects on the other marker sizes. 

I think the scaling should be changed so that low would spawn about 2-3, medium about 4-6, and high about 6-8.  If it can't though, I think replicating the old system as closely as possible should be the goal, since I've found that even for large groups of players the old medium village patrol spawn setting was plenty of AI.  I never really needed to use the high setting.  As it stands now I think there are just too many AI for markers of all sizes, and it drastically changes the balance and the performance of the mission.

Here's some screenshots demonstrating the issues:

NEW SYSTEM 

Village Patrol Spawn High spawns about 16
![ArmA 3 Screenshot 2019 12 24 - 14 31 28 28](https://user-images.githubusercontent.com/53233871/71426153-847e4000-265a-11ea-9750-6a790fe9fd2e.png)

Village Patrol Spawn Medium also spawns about 16
![ArmA 3 Screenshot 2019 12 24 - 14 28 06 30](https://user-images.githubusercontent.com/53233871/71426158-995ad380-265a-11ea-9cb0-da3e9ae069d6.png)

Village Patrol Spawn Low also spawns about 16
![ArmA 3 Screenshot 2019 12 24 - 14 22 11 20](https://user-images.githubusercontent.com/53233871/71426174-bb545600-265a-11ea-8b08-e6a848c9053f.png)

Mid city on fallujah Village Patrol Spawn Low still spawns at least a hundred patrols
![ArmA 3 Screenshot 2019 12 24 - 14 41 01 32](https://user-images.githubusercontent.com/53233871/71426231-6bc25a00-265b-11ea-9d53-c9a23fb838ec.png)


NEW SYSTEM GROUP SIZE
![ArmA 3 Screenshot 2019 12 24 - 15 20 32 82](https://user-images.githubusercontent.com/53233871/71426598-f78ab500-2660-11ea-906d-6495f921f5d0.png)
![ArmA 3 Screenshot 2019 12 24 - 15 20 42 51](https://user-images.githubusercontent.com/53233871/71426604-fc4f6900-2660-11ea-8f73-ecebcc4ab6d7.png)

OLD SYSTEM GROUP SIZE
![ArmA 3 Screenshot 2019 12 24 - 15 18 01 35](https://user-images.githubusercontent.com/53233871/71426582-b0042900-2660-11ea-913a-fdc3767d86dd.png)
![ArmA 3 Screenshot 2019 12 24 - 15 18 11 45](https://user-images.githubusercontent.com/53233871/71426583-b1355600-2660-11ea-8928-55cb70d75a57.png)
