### ISSUE TITLE
Extraction chopper landing unreliable on dedicated server.

### ISSUE THREAD

**Issue by dookiejones** [NeoArmageddon/co10_Escape#47]
The extraction chopper landing is unreliable at best on a windows dedicated server. Changing line 15 of fn_ExtractionChopper.sqf to the following corrects this behavior.
` _waypoint setWaypointStatements ["true", "(vehicle this) setvariable [""State"",""Land""]; vehicle this land 'LAND';"];`
[fn_ExtractionChopper.zip](https://github.com/NeoArmageddon/co10_Escape/files/4183917/fn_ExtractionChopper.zip)

**Comment by Qerbas** [comment]
I've worked a lot with Neo in the past with shaping up the extraction, and I've reworked a lot of the markers to space them out and put them in places where the helicopter lands more consistently, but I still notice some unreliability issues, so any improvements are always good.  What does this do specifically?

**Comment by dookiejones** [comment]
@Qerbas In editor placed waypoints you can put `vehicle this land 'LAND';` in activation as the... most forceful, for lack of a better term, way to make the AI land outside of unit capture which does not work on dedi. This simply adds the above to the waypoint.

**Comment by Qerbas** [comment]
What maps and extraction points were you having issues with specifically?  I'd like to see if I can do some side by side testing myself to see if there's any difference.

**Comment by dookiejones** [comment]
It was all maps, maybe 9 out of 10 times the chopper would fail to land. The above changes have made them land every time I have gotten that far since I implemented it.

**Comment by Qerbas** [comment]
Has to be something else then, do you know what version you're on?  Because on all of my maps with the reworked extraction markers the extraction is extremely reliable on a dedicated server, as long as they're not taking extremely heavy fire or you stand right on one of their landing points.

**Comment by NeoArmageddon** [comment]
In ~20 successful escapes the helis crashed one time only for us. I think this can be attributes to the A3 AI flying awefully.
