### ISSUE TITLE
Wartorn mode infantry spawning

### ISSUE THREAD

**Issue by dookiejones** [NeoArmageddon/co10_Escape#48]
This is possibly intentional but I will report anyway.

CUP mission, Wartorn mode on, RU v US Army v ION. 

US Army and ION will spawn in right on top of each other, with ION typically loosing the fight that ensues. It appears to be the village patrol spawns as I have never really noticed the distinct piles of bodies that it leaves behind outside of village patrol areas. I have been noticing these piles for a while now but I finally saw it happening while using Zeus to check for vehicles related to fn_MilitaryTraffic.sqf.

**Comment by Qerbas** [comment]
[Long standing bug that affected all versions of Wartorn that I discovered and Neo fixed.](https://github.com/NeoArmageddon/co10_Escape/issues/32).  Upgrade to one of the [Dev_191222 or newer](https://github.com/NeoArmageddon/co10_Escape/releases) versions for the fix.
