### ISSUE TITLE
Flags in some CUP configs are from CUP Terrains

### ISSUE THREAD

**Issue by Dystopian** [NeoArmageddon/co10_Escape#69]
If CUP Terrains are not loaded flags are missing.
https://github.com/NeoArmageddon/co10_Escape/blob/25bba7fee77e6b87c6fc301446bb306150c2dd76/Mods/CUP%20RU/UnitClasses.sqf#L16-L17
https://github.com/NeoArmageddon/co10_Escape/blob/25bba7fee77e6b87c6fc301446bb306150c2dd76/Mods/CUP%20SLA/UnitClasses.sqf#L16-L17

**Comment by ScruffyAT** [comment]
Was fixed in commit 5fa2d6d73750eeba754dc9f043660b7bbd6b4fec
