### ISSUE TITLE
Ace still doesnt work with escape

### ISSUE THREAD

**Issue by Pinkyyyy** [NeoArmageddon/co10_Escape#79]
I ran a dedicated server on my machine and connected to it. I was kind of excited to test escape with ace, but once i got killed (i was the only person playing so, even in regular escape this would have been a fail state) there was a timer, and once it ran out, i respawned with full gear. I saw a similar issue before, but i was hoping maybe this new update that says it imporved ace medical support would fix it, and it didnt. Could there be a way to force ai not to shoot you when youre down or just end the missions once you die instead of respawning

**Comment by Pinkyyyy** [comment]
I know some DRO missions have like a setting that turns off their revive scripts, so ace isnt broken, that works, ofc players can still die easily at the start, but could there be a way to force ace settings so it extends how much youre downed for, like so you dont bleed out as quickly, or to get up the first time youre downed, and add a few bandages, epis, morphine and blood in the starting backpack to aid the players in the beginning

**Comment by NeoArmageddon** [comment]
There is code in that disables the revive if ace medical is detected but looks like ACE updated their system in between where we added this and this release. I can try to add just another fix for the next update but as I normally don't play with ACE this is mostly up to other contributors.

**Comment by NeoArmageddon** [comment]
See https://github.com/NeoArmageddon/co10_Escape/blob/master/Code/functions/Common/fn_initLocalPlayer.sqf#L85 for reference

**Comment by Pinkyyyy** [comment]
Oh i see, bummer, i was hoping it got fixed, cuz the server i usually play on uses ace for other missions and then has to restart to disable it if we wanna do escape. If you ever get around to fixing it let me know! I know almost nothing about coding, i wish i could help
