### ISSUE TITLE
Add option to hide all enemy markers and add information collection from insurgency

### ISSUE THREAD

**Issue by NeoArmageddon** [NeoArmageddon/co10_Escape#92]
In my insurgency mission enemy randomly drop info caches that can be collected. 
This added to escape could pose an interesting new gameplay opportunity.
If the markers are not set to be always visible, collecting info could do one of these things:
- Reveal a formerly invisible marker on the map
- Change a questionmark to the correct location symbol

This would make engaging patrols beyond collecting map and ammo much more intresting.
Information collection could also be added to comcenter or a new type of outpost.

Additional input and ideas are highly appreciated!

**Comment by Dystopian** [comment]
2 current settings can be combined in 1 (`Disabled`,`5%`,`10%`,`20%`,`30%`,`40%`,`50%`). Can't make PR atm, let me know if it's needed.

**Comment by NeoArmageddon** [comment]
Would keep it seperate now to make it clear if the new system is activated or not. Also not sure the switch for the dropchance will stay in, was just for testing different values quickly (with CBA). Can be combined later if it stays in.

**Comment by NeoArmageddon** [comment]
Resolved by f46b63602fea4f891bbe04be1ea596515b78a6be
