### ISSUE TITLE
Earplugs within the mission

### ISSUE THREAD

**Issue by FlorianSW** [NeoArmageddon/co10_Escape#95]
In the Co10 Escape mission files for my server (go2tech.de) I've integrated some more scripts to support both administrating it as well as some functionality.

One of them is a earplugs script, which, when the F1 key is pressed, will reduce the surrounding sound by some percentage. It also shows a little icon (builtin) to indicate that earplugs are indicated.

I wrote this script (which is pretty simple tbh), as I don't want to require people to install a mod for such an easy functionality. As maintaining to import a script into the mission files is making it harder to update the mission files, I'm considering upstreaming this earplugs script here. However, with this issue I would clarify some things before doing so:
* Is such a script within the scope of the mission?
* Given I'm relatively new to ArmA mission scripting: Can you help me once I'm stuck at some point? :D

**Comment by NeoArmageddon** [comment]
Aloha FlorianSW,
I am not a huge fan of including many script to a mission that are not directly related to the missions gameplay. I find it much better to have this as optional addon for everybody in need of such a feature. Also F1 sounds a bit dangerous as default keybinding as it is used for the commanding menu.

But anyway feel free to create a pull request. If properly done with CBA keybindings this could be added without cluttering the params and assigning a custom key could be made completely optional.
