### ISSUE TITLE
fn_addIntel.sqf  needs edit

### ISSUE THREAD

**Issue by AKA-TiTAN** [NeoArmageddon/co10_Escape#99]
_chance is always 10%!

private _chance = missionnamespace getvariable ["A3_Param_IntelChance",10];

needs changing to 

private _chance = missionnamespace getvariable ["Param_IntelChance",10];

also does the } and the end of the script need to be };

the above changes work ok for me.

**Comment by NeoArmageddon** [comment]
The missing colon is intentional. The param name is intentional.

**Comment by AKA-TiTAN** [comment]
with my very limited scripting knowledge i still find this strange, when i changed the % chance in the params it didnt seam to do anything it was still hard to find intel on the bodies. i even added a 90% chance!. i can see that the params are stored in the mission namespace as variables and the param is called Param_IntelChance not A3_Param_IntelChance. as soon as i corrected this them the intel spawned on lots more AI.

**Comment by NeoArmageddon** [comment]
You are right but keep in mind this is a dev version and not meant to be played. The Variable has a different name because the param system gets a rewrite changing variable names. Also when CBA Settings is used, the variable actually IS changed by the param (because CBA uses A3E prefix).

**Comment by AKA-TiTAN** [comment]
Ah ok that makes sense. thought i was going mad!
